### ISSUE TITLE
大佬这是要搞什么大事

### ISSUE THREAD

**Issue by jinfagang** [pnnx/pnnx#1]
可以介绍一下吗？exchange 一个新的IR？还是要干啥

**Comment by F0xZz** [comment]
maybe this topic https://zhuanlan.zhihu.com/p/350395191

**Comment by nihui** [comment]
https://github.com/nihui/ncnn/tree/pnnx/tools/pnnx
写好了会open出来的～

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/427620428
https://www.bilibili.com/video/BV1Uv411u78D
