### ISSUE TITLE
转换yolov5s问题

### ISSUE THREAD

**Issue by zhongwenkun886** [pnnx/pnnx#12]
你好，我用PNNX转换yolov5s时，提示如下：
[W ..\..\aten\src\ATen\native\BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator ())
最终没有输出任何文件，请问如何解决？
非常感谢！

**Comment by zhiqwang** [comment]
可以先查看up新的 yolov5s pnnx 使用教程 https://zhuanlan.zhihu.com/p/471357671

**Comment by nihui** [comment]
这个 warning 可以不理会
以及，export torchscript 要有 --train 参数
