### ISSUE TITLE
5维输入, 导出 x_pnnx.py.onnx 时，grid_sample 没被导出

### ISSUE THREAD

**Issue by zchrissirhcz** [pnnx/pnnx#133]
# 复现步骤

## 环境
- Ubuntu 22.04
- Python 3.11.7
- torch: 2.2.2+cu121
- pnnx: 通过 pip install 安装， 版本 20240410

## 最小复现代码

x.py
```python
import torch

import torch.nn.functional as F


class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel,self).__init__()

    def forward(self, x, m):
        return F.grid_sample(x, m, align_corners=True, mode='bilinear', padding_mode='zeros')


# x = torch.rand(1, 1, 10, 10)
# m = torch.Tensor([[[1, 0, 0], [0, 1, 0]]])
# m = F.affine_grid(m, x.size()).type_as(x) # (1, 10, 10, 2)

x = torch.rand(4, 64, 8, 40, 60).cuda()
m = torch.rand(4, 7, 512, 128, 3).cuda()

print(x.shape)
print(m.shape)

model = MyModel()
model = model.eval()

# torch.onnx.export(
#     model,
#     (x, m),
#     "grid_sample.onnx",
#     verbose=True,
#     input_names=['input', 'grid'],
#     output_names=['output']
# )

net = model.eval()
mod = torch.jit.trace(net, (x, m))
mod.save("x.pt")
```

## step1
```bash
python x.py
```

## step2
```bash
pnnx ./x.pt inputshape="[[4,64,8,40,60],[4,7,512,128,3]]"
```

## step3
```bash
# edit x_pnnx.py, call export_onnx(), change to opset_version=17

def export_onnx():
    net = Model()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(4, 64, 8, 40, 60, dtype=torch.float)
    v_1 = torch.rand(4, 7, 512, 128, 3, dtype=torch.float)

    torch.onnx._export(net, (v_0, v_1), "./x_pnnx.py.onnx", export_params=True, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=17, input_names=['in0', 'in1'], output_names=['out0'])


if __name__ == "__main__":
    #print(test_inference())
    export_onnx()
```

## step4
```bash
python x_pnnx.py
```

得到 x_pnnx.py.onnx , 使用 netron 查看：

![image](https://github.com/pnnx/pnnx/assets/3831847/c96796a0-03db-4f06-ab48-e65ef7b0b362)

预期结果是和 x.pnnx.onnx 一样， 不显示为 Aten， 显示为 grid sample:

![image](https://github.com/pnnx/pnnx/assets/3831847/27f7ef21-d8f1-40de-b96b-8c1737d09281)

**Comment by zchrissirhcz** [comment]
GridSample-16 不支持5d输入

https://github.com/onnx/onnx/blob/main/docs/Changelog.md#gridsample-16
![image](https://github.com/pnnx/pnnx/assets/3831847/dda1c084-032c-4a66-819e-6a58344dee11)


GridSample-20 支持5d输入，即 opset 需要为 20

https://github.com/onnx/onnx/blob/main/docs/Changelog.md#gridsample-20
![image](https://github.com/pnnx/pnnx/assets/3831847/65ac2e3d-02b4-493d-a36e-21f7400c3789)


PyTorch 官方似乎不打算支持 opset 19 和 opset 20:
https://github.com/pytorch/pytorch/issues/114801

![image](https://github.com/pnnx/pnnx/assets/3831847/c63a6635-4e22-40dd-963d-0130be0d47f5)

**Comment by zchrissirhcz** [comment]
另外提供一种思路是 dynamo 的 export onnx.

https://pytorch.org/docs/stable/onnx_dynamo.html

**Comment by tianlinzx** [comment]
@zchrissirhcz Have you fixed your issue ?
would you please share your idea how to use onnx_dynamo?
Thanks for your help in advance.

**Comment by liaoqingPKU** [comment]
> @zchrissirhcz Have you fixed your issue ? would you please share your idea how to use onnx_dynamo? Thanks for your help in advance.
I fixed this issue by method below：
First export onnx with opset=16 through export.onnx, and then use onnx_graphsurgeon to directly modify the opset to 20. You can walk around this problem to support GridSample 5D

**Comment by zmtttt** [comment]
hi！ I export opset16 -onnx，and use onnx_graphsurgeon to directly modify the opset to 20，but meet the same problem @ @liaoqingPKU @zchrissirhcz

**Comment by zmtttt** [comment]
[05/28/2024-16:01:24] [I] TensorRT version: 8.6.1
[05/28/2024-16:01:24] [I] Loading standard plugins
[05/28/2024-16:01:24] [I] [TRT] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 18, GPU 271 (MiB)
[05/28/2024-16:01:28] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +1449, GPU +266, now: CPU 1544, GPU 537 (MiB)
[05/28/2024-16:01:28] [I] Start parsing network model.
[05/28/2024-16:01:28] [I] [TRT] ----------------------------------------------------------------
[05/28/2024-16:01:28] [I] [TRT] Input filename:   simple_op20.onnx
[05/28/2024-16:01:28] [I] [TRT] ONNX IR version:  0.0.10
[05/28/2024-16:01:28] [I] [TRT] Opset version:    20
[05/28/2024-16:01:28] [I] [TRT] Producer name:    
[05/28/2024-16:01:28] [I] [TRT] Producer version: 
[05/28/2024-16:01:28] [I] [TRT] Domain:           
[05/28/2024-16:01:28] [I] [TRT] Model version:    0
[05/28/2024-16:01:28] [I] [TRT] Doc string:       
[05/28/2024-16:01:28] [I] [TRT] ----------------------------------------------------------------
[05/28/2024-16:01:28] [W] [TRT] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/28/2024-16:01:29] [E] Error[3]: [network.cpp::addGridSample::1537] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/network.cpp::addGridSample::1537, condition: input.getDimensions().nbDims == 4
)
Segmentation fault (core dumped)

**Comment by HSDai** [comment]
> trtexec --onnx=simple_op20.onnx --saveEngine=simple_op20.engine
> 
> [05/28/2024-16:01:24] [I] TensorRT version: 8.6.1 [05/28/2024-16:01:24] [I] Loading standard plugins [05/28/2024-16:01:24] [I] [TRT] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 18, GPU 271 (MiB) [05/28/2024-16:01:28] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +1449, GPU +266, now: CPU 1544, GPU 537 (MiB) [05/28/2024-16:01:28] [I] Start parsing network model. [05/28/2024-16:01:28] [I] [TRT] ---------------------------------------------------------------- [05/28/2024-16:01:28] [I] [TRT] Input filename: simple_op20.onnx [05/28/2024-16:01:28] [I] [TRT] ONNX IR version: 0.0.10 [05/28/2024-16:01:28] [I] [TRT] Opset version: 20 [05/28/2024-16:01:28] [I] [TRT] Producer name: [05/28/2024-16:01:28] [I] [TRT] Producer version: [05/28/2024-16:01:28] [I] [TRT] Domain: [05/28/2024-16:01:28] [I] [TRT] Model version: 0 [05/28/2024-16:01:28] [I] [TRT] Doc string: [05/28/2024-16:01:28] [I] [TRT] ---------------------------------------------------------------- [05/28/2024-16:01:28] [W] [TRT] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32. [05/28/2024-16:01:29] [E] Error[3]: [network.cpp::addGridSample::1537] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/network.cpp::addGridSample::1537, condition: input.getDimensions().nbDims == 4 ) Segmentation fault (core dumped)

Did you succeed with this method those days?

**Comment by larrygoyeau** [comment]
> trtexec --onnx=simple_op20.onnx --saveEngine=simple_op20.engine
> 
> [05/28/2024-16:01:24] [I] TensorRT version: 8.6.1 [05/28/2024-16:01:24] [I] Loading standard plugins [05/28/2024-16:01:24] [I] [TRT] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 18, GPU 271 (MiB) [05/28/2024-16:01:28] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +1449, GPU +266, now: CPU 1544, GPU 537 (MiB) [05/28/2024-16:01:28] [I] Start parsing network model. [05/28/2024-16:01:28] [I] [TRT] ---------------------------------------------------------------- [05/28/2024-16:01:28] [I] [TRT] Input filename: simple_op20.onnx [05/28/2024-16:01:28] [I] [TRT] ONNX IR version: 0.0.10 [05/28/2024-16:01:28] [I] [TRT] Opset version: 20 [05/28/2024-16:01:28] [I] [TRT] Producer name: [05/28/2024-16:01:28] [I] [TRT] Producer version: [05/28/2024-16:01:28] [I] [TRT] Domain: [05/28/2024-16:01:28] [I] [TRT] Model version: 0 [05/28/2024-16:01:28] [I] [TRT] Doc string: [05/28/2024-16:01:28] [I] [TRT] ---------------------------------------------------------------- [05/28/2024-16:01:28] [W] [TRT] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32. [05/28/2024-16:01:29] [E] Error[3]: [network.cpp::addGridSample::1537] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/network.cpp::addGridSample::1537, condition: input.getDimensions().nbDims == 4 ) Segmentation fault (core dumped)

Same problem.
