### ISSUE TITLE
pnnx-20231010-ubuntu可以转成功，但是最新版不能

### ISSUE THREAD

**Issue by wxqwinner** [pnnx/pnnx#161]
jit模型，
```bash
./pnnx silero.jit inputshape=[1,512],[2,1,64],[2,1,64]
```
[silero.zip](https://github.com/user-attachments/files/16491856/silero.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5632

**Comment by wxqwinner** [comment]
pnnx==20240819 OK, nihui YES!!!
