### ISSUE TITLE
PNNX会开源吗？

### ISSUE THREAD

**Issue by gaojing8500** [pnnx/pnnx#2]

**Comment by zhiqwang** [comment]
URL: https://github.com/Tencent/ncnn/pull/3262

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/3262

**Comment by oblessnoob** [comment]
https://github.com/nihui/ncnn/tree/pnnx/tools/pnnx

**Comment by nihui** [comment]
已经合入主干
https://github.com/Tencent/ncnn/tree/master/tools/pnnx
