### ISSUE TITLE
is there way merge activation into nn.Linear for normal [nn.Linear + act] partten?

### ISSUE THREAD

**Issue by jinfagang** [pnnx/pnnx#34]
Hi, is there way to merge activation into nn.Linear for normal [nn.Linear + act] partten?
this would avoid add another activation layer behind also avoid unncessary memcpy to reduce both Mem usage and speed (very little).

**Comment by nihui** [comment]
The op definition of pnnx comes from pytorch, pytorch does not have an op such as linear+activation, so pnnx cannot do such a merge optimization.

In addition, there is such a combination in the op definition of ncnn, so it will be automatically merged and optimized when converting to ncnn. [0]

[0] https://github.com/Tencent/ncnn/blob/master/tools/pnnx/src/pass_ncnn/fuse_innerproduct_activation.cpp

**Comment by jinfagang** [comment]
@nihui thanks, I'll reference to the pass_ncnn
