### ISSUE TITLE
Some torch operators are not supported yet

### ISSUE THREAD

**Issue by niuxingzhen** [pnnx/pnnx#4]

**Comment by nihui** [comment]
please provide your pytorch model or torchscript pt with tracing

**Comment by niuxingzhen** [comment]
大佬好！
&nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; 我这个torchscript pt文件有点大，issues上限制100M，
所以放到附件里了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pnnx/pnnx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月31日(星期五) 下午2:58
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [pnnx/pnnx] Some torch operators are not supported yet (Issue #4)





 
please provide your pytorch model or torchscript pt with tracing
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

net_F.torchscript.zip (321.72M, 2022年01月30日 15:04 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7e666335ba14d78e62ecc47f1762014a0450540c0757030019545604014f075700044e0c50540b485055500c54000051055151533177330b51123c731f165c17570e1056430b43111a1c0a45315f&code=4fc51b3e

**Comment by nihui** [comment]
the missing operators
```
torch.norm
torch.stack
torch.index (numpy advanced indexing)
```

**Comment by niuxingzhen** [comment]
感谢大佬回复，如下图分别是torch.norm(), torch.stack(), torch.index
![图片1](https://user-images.githubusercontent.com/41133684/147832900-51c55620-953a-4bdb-b651-9cc1ae3067c8.png)

**Comment by nihui** [comment]
torch.norm and torch.stack pnnx conversion implemented

**Comment by nihui** [comment]
Tensor index https://github.com/Tencent/ncnn/pull/3483

**Comment by niuxingzhen** [comment]
up太强了！！！
