### ISSUE TITLE
请加上pnnx程序的输入数据文件类型检测

### ISSUE THREAD

**Issue by znsoftm** [pnnx/pnnx#41]
使用pnnx转换模型，由于不熟悉，输入torch.save的模型，直接非法操作退出，没有提示，没有产出物。偶尔发现它只接受torch.jit.save后的模型。

建议在pnnx程序上加上检测，如果是torch.save的模型或其它不认识的模型，直接报错退出。

**Comment by nihui** [comment]
已实现
