### ISSUE TITLE
pnnx binary expression 扩展问题

### ISSUE THREAD

**Issue by jinfagang** [pnnx/pnnx#59]
Hi，pnnx默认对于expression有时候会折叠（尽管不确定为什么要这样）：

```
pnnx.Expression          pnnx_expr_38             3 1 166 161 163 167 expr=div(@0,add(sqrt(add(mul(@1,@1),mul(@2,@2))),1.800000e+00)) #166=(64,64,17)f32 #161=(64,64,17)f32 #163=(64,64,17)f32 #167=(64,64,17)f32

```

我们正打算基于pnnx做一套parse，这种折叠对转换带来了很多麻烦，有办法可以把这种折叠默认去掉吗？（我看ncnn的pass又会展开，所以我认为这种表征方式没有任何意义）

**Comment by nihui** [comment]
合并为一个表达式，有助于后端更激进的 fuse
通常这类 element-wise 的操作组合，可以在一次遍历中实现
ncnn 暂时还不具备这优化，所以又展开了

**Comment by jinfagang** [comment]
已解决。

**Comment by zjhellofss** [comment]
我遇到了楼主一样的问题。
我的解决办法给大家参考一下，
1. 使用 读取expr中的内容形成token数组，并进行有效token的校验（token种类包括{, }, (, ), add, mul等）。
2. 再对token数组进行递归下降分析形成一棵parse tree, 再将parse tree转为逆波兰序列。
3. 在forward的时候根据逆波兰序列中的顺序执行。

总体对我来讲，确实这种折叠方式不好处理。
