### ISSUE TITLE
Unknown builtin op: aten::scaled_dot_product_attention.Any help?

### ISSUE THREAD

**Issue by followtheart** [pnnx/pnnx#79]
root@jq-hasee:~/pnnx-20230227-ubuntu# ./pnnx ~/vit_b_16.pt inputshape=[1,3,224,224]
pnnxparam = /root/vit_b_16.pnnx.param
pnnxbin = /root/vit_b_16.pnnx.bin
pnnxpy = /root/vit_b_16_pnnx.py
pnnxonnx = /root/vit_b_16.pnnx.onnx
ncnnparam = /root/vit_b_16.ncnn.param
ncnnbin = /root/vit_b_16.ncnn.bin
ncnnpy = /root/vit_b_16_ncnn.py
fp16 = 1
optlevel = 2
device = cpu
inputshape = [1,3,224,224]f32
inputshape2 =
customop =
moduleop =
terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():
Unknown builtin op: aten::scaled_dot_product_attention.
Here are some suggestions:
        aten::_scaled_dot_product_attention

The original call is:
  File "code/__torch__/torch/nn/modules/activation/___torch_mangle_600.py", line 59
    k1 = torch.view(k0, [_5, 12, _25, _9])
    v1 = torch.view(v0, [_4, 12, _24, _8])
    attn_output = torch.scaled_dot_product_attention(q1, k1, v1)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _26 = torch.permute(attn_output, [2, 0, 1, 3])
    attn_output0 = torch.view(torch.contiguous(_26), [int(torch.mul(bsz, tgt_len)), _7])

Aborted

**Comment by followtheart** [comment]
After some struggle to down-grade  protobuf to support c++11;then can "Use pytorch-2.0 to compile pnnx by yourself"
and finally ,my model parsed;and thx a lot

**Comment by nihui** [comment]
new package build with pytorch-2.0
https://github.com/pnnx/pnnx/releases/tag/20230418
