### ISSUE TITLE
PNNX aarch64 compatibility

### ISSUE THREAD

**Issue by jeck00119** [pnnx/pnnx#86]
Hello! Could you add at releases a pnnx binary for aarch64 (Raspberry Pi 4 or Nvidia Jetson Nano), because when I run the ubuntu binary I get 
`bash: ./pnnx: cannot execute binary file: Exec format error`

**Comment by StuartIanNaylor** [comment]
If you could as Aarch64 and the edge is very much a target platform even for the conversion process

**Comment by lakshanthad** [comment]
@jeck00119 Are you able to successfully build for Raspberry Pi Bookworm OS?

**Comment by nihui** [comment]
pnnx now provides binaries for macos arm64 and pypa wheel

The distribution of linux aarch64 pnnx should have no technical obstacles and will be available sometime in the near future :D

**Comment by nihui** [comment]
pnnx linux aarch64 binary package and pypi wheel are provided since 20240226 :)
