### ISSUE TITLE
How to convert multi input net to pnnx?

### ISSUE THREAD

**Issue by hhxdestiny** [pnnx/pnnx#90]
Hi, my model input is shown in the following figure. How can I set the inputshape to support my model?
![image](https://github.com/pnnx/pnnx/assets/44420757/37b78a51-7bf4-4183-85ef-e6debc8f92ba)

**Comment by nihui** [comment]
```
inputshape=[1,feats_length,400],[1,128,19,1],[1,128,19,1], ......
```

**Comment by hhxdestiny** [comment]
> feats_length
Thank you for your reply. feats_length is dynamic, so it's definitely incorrect to write it like this, but giving it -1 doesn't seem to work either. I remember which model Yolov5 used, and if the output is dynamic, it needs to be changed to -1 in. param
```bash
(pytorch) PS D:\ncnn> .\pnnx.exe model.pt inputshape=[1,feats_length,400],[1,128,19,1],[1,128,19,1],[1,128,19,1],[1,128,19,1]
···
fp16 = 1
optlevel = 2
device = cpu
inputshape = [1]f32,[1,128,19,1]f32,[1,128,19,1]f32,[1,128,19,1]f32,[1,128,19,1]f32
···
```

**Comment by wuhongsheng** [comment]
> ```
> inputshape=[1,feats_length,400],[1,128,19,1],[1,128,19,1], ......
> ```

大佬这个input应该怎么写
![image](https://github.com/user-attachments/assets/fa107e7d-2548-441e-88ee-058f6d526d38)
